# Site settings
title: Tanul Christian
twitter_username: ChristianTanul
name: Tanul Christian

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/chriskryx
 - title: StackOverflow
   url: https://stackoverflow.com/users/10699002/christi-tanul
 - title: LinkedIn
   url: www.linkedin.com/in/tanul-christian-94333a17a

#Any buzzword skills you want to include
skills:
 - Python
 - WordPress
 - Machine learning
 - Tensorflow
 - Django

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
 - title: WordPress Web Developer
   start: 2018
   end: Ongoing
   employer: Basement Crowd
   description: Legaltech startup producing a range of innovative legal products.

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2017
   subject: Artificial Intelligence and Computer Science
   school: University of Groningen

#This section is optional (as is the image link below)
coursera:
   profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
   courses:
    - title: Functional Programming Principles in Scala
      link: https://www.coursera.org/course/progfun
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
      date: September 16, 2013
    - title: Algorithms Design and Analysis, Part 1
      link: https://www.coursera.org/specializations/algorithms
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
      date: April 28, 2014
      
#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
speakerdeck:
   profileurl: https://speakerdeck.com/robhinds
   talks:
    - title: Product Management for Engineers
      speakerdeckId: 94f0070c4e434ec79fe9b4eb2cb574e0
      conference: API Conference, Berlin 2018
    - title: Agile Machine Learning - from Theory to Production
      speakerdeckId: ec84f2f56e9743afb0675b1eeeb6b6ce
      conference: W-JAX Conference, Munich 2017 (London 2017)

#List of interesting Github repo/projects to include - optional
github:
 - robhinds/robhinds.github.io
 - robhinds/ScaLambda
 - robhinds/opinionated-akka-http
 - robhinds/food2vec
 - robhinds/microservices
 - robhinds/spring-social-geeklist
 - robhinds/spring-social-stackoverflow
 - robhinds/genotype
 - robhinds/footweets
 - robhinds/ElasticSearchGradle

#Stackoverflow flair is optional
stackoverflow:
   profileurl: https://stackoverflow.com/users/10699002/christi-tanul
   flairimageurl: https://stackoverflow.com/users/10699002/christi-tanul

intro: |
  I am a self-taught programmer with 3 years of experience. I have primarily worked in Python, and came across quite some technologies and frameworks thereon such as Django, Web Scraping, Tensorflow and Keras. <br/><br/>
  Nothing can thrill me more than the dopamine of finally finding the solution to a problem.<br/><br/>
  During the past 2 years I have spent a reasonable amount of time building websites for different clients, which has given me an exposure to using WordPress. <br/><br/>
  Have always tried to use my knowledge in Python to automate tasks in my life, such as using web scraping to find companies that might need a better website.<br/><br/>
#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>WordPress</strong>: By using Wordpress I have exposed myself to a little bit of HTML and CSS. I am familiar with most functionalities of WordPress. <br/><br/>
   <strong>Design</strong>: Even though it is not related with my coding experience, knowledge in Photoshop, After Effects and Premiere Pro is part of my skillset as well. I have used them for some side income by freelancing. <br/><br/>
   
   
